### ISSUE TITLE
1. Centralization or the Requirement of Trust is Unacceptable

### ISSUE THREAD

**Issue by taariq** [DavidAJohnston/TheValueofAppCoins#10]
I think this has an issue because when we say "Centralization of Trust is unacceptable" it's not clear what is the opposite of "centralization of trust". How do you decentralize trust? When is decentralization of trust acceptable?

For example: 
When an AppCoin issues a new currency, is that a decentralized action or a centralized action?  It would seem that coin issuance cannot be decentralized. Only one entity can issue any particular AppCoin.

When an AppCoin pays a dividend, is that a non-centralized action? Is there any protocol where a specific actor/administrator of the coin doesn't have to actually make the dividend payment?

Conclusion: If you take the opposite of the statement "Centralization or the Requirement of Trust is unacceptable" you get "The Decentralization of or the Non-Requirement of Trust is Acceptable" and that doesn't make sense when you say it out loud. 

Trust is something between agents. The idea that trust can be decentralized is problematic and doesn't seem logical. I would propose that that trustless systems can be more trustworthy than trusted systems, but it doesn't mean that trustless systems are decentralized systems themselves. 

Someone may wish to rewrite the that first assertion for added logic and clarity.

**Comment by DavidAJohnston** [comment]
Thanks for the thoughts Taariq. I welcome pull requests to improve this section.

**Comment by taariq** [comment]
You got it. I will submit some updates and try not to embarrass myself.

**Comment by taariq** [comment]
AppCoins are so different today. Closing.
